name: '📑 Changelog Builder'

on:
  release:
    types: [created]

jobs:
  release:
    if: startsWith(github.ref, 'refs/tags/')
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        
      - name: Build Changelog
        id: github_release
        uses: mikepenz/release-changelog-builder-action@v2
        with:
          configuration: "./changelog-configuration.json"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          
      - name: Get the version
        id: get_version
        run: echo ::set-output name=VERSION::$(echo $GITHUB_REF | cut -d / -f 3)
          
      - name: Update GitHub Release
        uses: tubone24/update_release@v1.3.1
        with:
          release_name: ${{ steps.get_version.outputs.VERSION }}
          body: ${{steps.github_release.outputs.changelog}}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}